package com.message;

public enum AdminMessage {
    BLOCK_ACC,
    UNBLOCK_ACC,
    ADD_ADMIN,
    UPDATE_STATISTIC,
    UPDATE_COMMENT,
    UPDATE_ACC,
    UPDATE_EMPLOYEE,
    EXIT, ADD_ROOM, UPDATE_ALL_ROOM, REMOVE_ACCOUNT, СHANGE_PERS_ACC, ADD_EMOLOYEE, VIEW_ROOM, REMOVE_ROOM, OPEN_ROOM, STOP_ROOM, REPAIR_ROOM, REMOVE_EMPLOYEE, REGISTRATION_EMPLOYEE,
}
